---
title: "CH3/40220"
subtitle: "Crown ethers and derivatives"
author: "Fiona Dickinson"
date: "03/02/2022"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Course Timetable

- Week 1: <span style="color:lightgrey">In Person - Intro to the course, refresher course on thermodynamics</span>
- Week 2: <span style="color:lightgrey">LOIL - Lecture - Crown & lariat ethers and related molecules</span>
- Week 3: <span style="color:crimson">In Person - Workshop (research paper based exercise)</span>
- Week 4: <span style="color:darkturquoise">LOIL - Lecture - Self assembly the basics, DNA duplexing and beyond</span>
- Week 5: In Person - Workshop (research paper based exercise) 
- Week 6: <span style="color:darkturquoise">LOIL - Lecture - Tertiary structures</span>
- Week 7: In Person - Workshop (research paper based exercise)
- Week 8: <span style="color:darkturquoise">LOIL - Lecture - Binding of small molecules to biopolymers</span>
- Week 9: In Person - Workshop (research paper based exercise)
- Week 10: <span style="color:darkturquoise">LOIL - Lecture - Solvation, hydrodynamics & osmosis</span>
- Week 11: In Person - Workshop example exam questions


## The workshop

[Selectivity of Xcrown-4 complexes to lithium ions](http://libproxy.bath.ac.uk/login?url=https://pubs.acs.org/doi/abs/10.1021/jo00072a024)

[Thermodynamics of cryptand binding](http://libproxy.bath.ac.uk/login?url=https://pubs.acs.org/doi/pdf/10.1021/ja00856a018)

[Thermodynamics of spherand binding](http://libproxy.bath.ac.uk/login?url=https://onlinelibrary.wiley.com/doi/epdf/10.1002/anie.198610393)

## Workshop - 1

**Crown ether paper**

- Is the enthalpy of binding just a property of the number of bonds made?

- If not what factors affect the enthalpy of binding?

In all cases the binding is endothermic with a positive entropy change. Does this make the binding more or less favorable at  higher temperatures?

- The 'benzo rings' have negative entropy contriubtions, whereas the 'plain' crown ethers do not. Why may this be the case?

## Workshop - 2

**Cyptate paper**

- Given Li^+^ and Mg^2+^ have approximately the same ionic radius suggest why there is such a large difference in the binding constant K~b~ (5.5 & 2.5 respectively) to [2.1.1]cryptate.

- Suggest why moving from 95:5 MeOH:H~2~O to water decreases complex stability.

- For the K^+^ the diaza-crown (8), the lariat ether (9) and the [2.2.1]cryptand shows a marked increase in binding constant (K~b~ = 4.38, 4.80 & 7.45 respectively). Explain this in terms of the thermodynamics of binding.

## Workshop - 3

**Spherand paper**

p1048

- There is a large difference in the binding constant of Li^+^ when moving from molecule *10* - *3* - *8*, justify this in terms of the structure of the spherands and the effect this will have on the thermodynamics.

- Why is this effect different (and less pronounced) for K^+^ binding?

- Why is the binding more favorable than for molecule *4* the equivalent cryptand for *8*?

## General notes

Do you understand how to read a 'Lehn diagram'.
